### ISSUE TITLE
Change Caption style for Persian

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#376]
**Is your feature request related to a problem? Please describe.**
Arises from #270, but worth encapsulating as an issue in its own right.

For Persian, the plan is that the caption will not be in italic. Regardless, on all services the font in captions is a different colour from the font in body text.

**Describe the solution you'd like**
A CSS-only solution, something along the lines of:

```scss
figcaption {
  font-style: italic;
  em {
    font-style: normal;
  }

  [lang=fa] & {
    font-style: normal;
    em {
        font-style: ???; /* italic text not a thing in Persian. TBC! */
    }
  }
}
```

**Describe alternatives you've considered**
We could update the Psammead Caption component to take in a prop 'italicisation' to be true by default but false for Persian.
There should be a list of scripts which should have italics off.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)
