### ISSUE TITLE
Ambiguous Typography documentation

### ISSUE THREAD

**Issue by cseas** [BBC-archive/psammead#3909]
The [Typography stories](https://bbc.github.io/psammead/?path=/docs/others-typography--atlas) only include instructions on how to install the package and not how to use it.

The **Usage** section just mentions this:
```jsx
import { C_POSTBOX } from '@bbc/psammead-styles/colours';
import { F_REITH_SANS_REGULAR, F_REITH_SANS_ITALIC } from '@bbc/psammead-styles/fonts';
```

Okay, imported. But what to do after that? From those imports, how does someone get to displaying the Trafalgar font for example?

**Comment by cseas** [comment]
I was able to make *something* work by using the following code:

```css
// global styles

  @font-face {
    font-display: optional;
    font-family: 'ReithSans';
    font-style: normal;
    font-weight: 400;
    src: url('https://gel.files.bbci.co.uk/r2.511/BBCReithSans_W_Rg.woff2')
        format('woff2'), url('https://gel.files.bbci.co.uk/r2.511/BBCReithSans_W_Rg.woff')
        format('woff');
  }
  
  @font-face {
    font-display: optional;
    font-family: 'ReithSerif';
    font-style: normal;
    font-weight: 600;
    src: url('https://gel.files.bbci.co.uk/r2.511/BBCReithSerif_W_Md.woff2')
        format('woff2'), url('https://gel.files.bbci.co.uk/r2.511/BBCReithSerif_W_Md.woff')
        format('woff');
  }
```

```tsx
// styled component

import { latin } from "@bbc/gel-foundations/scripts";
import { getRoyal } from "@bbc/gel-foundations/typography";
import { getSerifMedium } from "@bbc/psammead-styles/font-styles";

const SubHeading = styled.h2`
  ${getRoyal(latin)};
  ${getSerifMedium("news")};
`;
```

```tsx
// usage

        <SubHeading>
          Could a computer ever create better art than a human?
        </SubHeading>
```

However, the result looks very different compared to the example shown in the [BBC storybook](https://bbc.github.io/psammead/?path=/docs/others-typography--royal).

---
**In storybook:**
![Selection_001](https://user-images.githubusercontent.com/29686866/96350355-22079c00-10d3-11eb-9b80-f4c9da9372fb.png)

---
**In the above code implementation:**
![Selection_002](https://user-images.githubusercontent.com/29686866/96350377-36e42f80-10d3-11eb-9baf-8f2d81f8e8fa.png)

Is there something I'm missing?
