### ISSUE TITLE
Add Nassim font faces to psammead-styles

### ISSUE THREAD

**Issue by 12** [BBC-archive/psammead#675]
**Is your feature request related to a problem? Please describe.**
Add these font faces to `psammead-styles`:
```css
@font-face {
  font-family: "NassimPersian";
  font-weight: 700;
  font-style: normal;
  src: url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/bold.woff') format('woff'), url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/bold.eot') format('eot'), url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/bold.ttf') format('ttf');
  font-display: optional;
}

@font-face {
  font-family: "NassimPersian";
  font-weight: 400;
  font-style: normal;
  src: url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/normal.woff') format('woff'), url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/normal.eot') format('eot'), url('https://ws-downloads.files.bbci.co.uk/fonts/NassimPersian/v1.511/normal.ttf') format('ttf');
  font-display: optional;
}
```

**Describe the solution you'd like**
Add them to fonts in `psammead-styles`, namespace them as `F_NASSIM_PERSIAN_REGULAR` and `F_NASSIM_PERSIAN_BOLD`.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Unit test to ensure exports exist.

**Additional context**
